### ISSUE TITLE
Can u support more examples in  difference language such as JAVA?

### ISSUE THREAD

**Issue by LoveqLRC** [kakajika/RelativePopupWindow#1]
Can u support more examples in  difference language such as JAVA?

**Comment by kakajika** [comment]
Yes.
Ok, I'll add one in Java.

**Comment by kakajika** [comment]
I added Java example under package [`com/labo/kaji/relativepopupwindow/example/java`](https://github.com/kakajika/RelativePopupWindow/tree/master/example/src/main/java/com/labo/kaji/relativepopupwindow/example/java).
It behaves the same way as Kotlin example.
