### ISSUE TITLE
Bug: can't show on RecyclerView views as anchors, or makes it scroll in other cases

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [kakajika/RelativePopupWindow#11]
I've noticed that if you set RecyclerView views as anchors, and I click on one of the bottom ones of the screen, it doesn't get shown.

This is when I use WRAP_CONTENT for width and height of the popup.

If I try to set width and height myself, I've noticed that it sometimes scrolls the RecyclerView.

Attached video and sample project to show issues:

[MyApplication.zip](https://github.com/kakajika/RelativePopupWindow/files/3455669/MyApplication.zip)
[2019-08-01_11-31-43.zip](https://github.com/kakajika/RelativePopupWindow/files/3455670/2019-08-01_11-31-43.zip)

Please fix those issues.

**Comment by kakajika** [comment]
Hi,

> I've noticed that if you set RecyclerView views as anchors, and I click on one of the bottom ones of the screen, it doesn't get shown.
>
> This is when I use WRAP_CONTENT for width and height of the popup.

Okay, I'll fix the problem. Check next release of this library.

> If I try to set width and height myself, I've noticed that it sometimes scrolls the RecyclerView.

It may be due to the LayoutManager.
You can avoid that behavior by the following code:

```kotlin
layoutManager = object : GridLayoutManager(context, 3) {
    override fun requestChildRectangleOnScreen(
        parent: RecyclerView, child: View, rect: Rect, immediate: Boolean
    ): Boolean {
        return false
    }
}
```

**Comment by AndroidDeveloperLB** [comment]
What does "requestChildRectangleOnScreen" do? Why do I need to change it for the popup you have here, but it doesn't have any issues when I use a different solution (like ContextMenu) ? 

Please try to have a fix that doesn't require this change.

**Comment by kakajika** [comment]
See this:
https://stackoverflow.com/questions/29473977/popupmenu-click-causing-recyclerview-to-scroll

Anyway, the problem should be fixed by new layout logic in my latest release: `v0.4.1`. So you should no longer need this change.
Please check it.

**Comment by AndroidDeveloperLB** [comment]
ok thanks

**Comment by AndroidDeveloperLB** [comment]
But what does this function do?
