### ISSUE TITLE
how to add an animation style on popwindow like this...

### ISSUE THREAD

**Issue by zaaach** [kakajika/RelativePopupWindow#4]
![qq 20161206113505](https://cloud.githubusercontent.com/assets/9695127/20912095/1df06ce8-bba8-11e6-8905-fdc3bd691938.gif)
this popwindow shows from the bottom of the titlebar, how to make it.

**Comment by kakajika** [comment]
Sorry, this library is for controlling position of PopupWindow, and it's not responsible for Animations.
